### ISSUE TITLE
setUserIdentifier alternative

### ISSUE THREAD

**Issue by giulianok** [smartlook/cordova-smartlook#33]
`setUserIdentifier` is deprecated as per the typescript definition

<img width="1023" alt="Screen Shot 2022-07-07 at 11 58 00 AM" src="https://user-images.githubusercontent.com/8062245/177819013-17b3ddb6-9b26-4c5a-9cc1-4998a8cbce51.png">

What should be used instead? The following screenshot if from a Smartlook recording

<img width="364" alt="Screen Shot 2022-07-07 at 11 59 52 AM" src="https://user-images.githubusercontent.com/8062245/177819097-7a057800-4a1d-43ac-b7ed-6c919d9e1a29.png">

**Comment by sneko** [comment]
@SenNeonoveNoci @pavel-kroh-smartlook any idea?

**Comment by sneko** [comment]
I'm using:
```
    "@ionic-native/smartlook": "^5.36.0",
```

and don't have this warning. Maybe you use the `@awesome-cordova-plugins/smartlook` package? Don't know which one should be used.

Can't know the difference because they are released within larger project versioning:
https://www.npmjs.com/package/@awesome-cordova-plugins/smartlook
https://www.npmjs.com/package/@ionic-native/smartlook

**Comment by c0mtru1se** [comment]
Hi!
This is indeed a weird error as no such deprecation is specced in the TS code. 
If you're still interested in using Smartlook, I will be starting the work to support our new 2.x+ SDKs in the coming days, with the ETA in the coming weeks. The API will be rewritten and (hopefully) less error-prone as we partially already battle-tested it in our React Native SDK.
I will also take full support of Smartlook Cordova / Ionic plugins with the new and future versions.
Thanks!
